### ISSUE TITLE
Add box to modal that asks about the role of the user, with options

### ISSUE THREAD

**Issue by allthesignals** [tulsa-policy-institute/masthead#1]
Options are (single select):

- I work at the City of Tulsa
- I have run for City Council
- I work at a nonprofit
- I am a business owner
- I am a resident of Tulsa

This data will be included with user metadata for analytics and will prefill the ask-a-question form.

Explore if multi-select will work for this.

**Comment by samuelsaccount** [comment]
I do not see these options. Is this you wanting me to review this?

**Comment by samuelsaccount** [comment]
I got it!
