### ISSUE TITLE
(Complete by 8/23) - Integrate Abby’s aesthetic (see Abby for more)

### ISSUE THREAD

**Issue by allthesignals** [tulsa-policy-institute/masthead#3]
Please complete by 8/23. Abby's redesign of the website, including landing page - seamless transition to questions coming up from the bottom, new icons, background moving question, etc.

**Comment by samuelsaccount** [comment]
Yes! That is it. The video is super cool! Can't wait to see this in action :)

**Comment by abby-mz** [comment]
its a gif in the mockup in Figma, but you should use the Vimeo link to embed it as a background video on the site
https://tpi-rsm2096.slack.com/archives/C03MQ5K741F/p1660854681372179
